version: '3.3'
services:
   db:
      image: postgres:12-alpine
      environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
      ports:
      - 5437:5432
      expose:
      - 5432
